node dts-google-apps-script-advanced/index.js data_3/adsence_v1_4.json > DefinitelyTyped/types/google-apps-script/apis/adsence_v1_4.d.ts
node dts-google-apps-script-advanced/index.js data_3/analytics_v3.json > DefinitelyTyped/types/google-apps-script/apis/analytics_v3.d.ts
node dts-google-apps-script-advanced/index.js data_3/analyticsreporting_v4.json > DefinitelyTyped/types/google-apps-script/apis/analyticsreporting_v4.d.ts
node dts-google-apps-script-advanced/index.js data_3/appsactivity_v1.json > DefinitelyTyped/types/google-apps-script/apis/appsactivity_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/bigquery_v2.json > DefinitelyTyped/types/google-apps-script/apis/bigquery_v2.d.ts
node dts-google-apps-script-advanced/index.js data_3/calendar_v3.json > DefinitelyTyped/types/google-apps-script/apis/calendar_v3.d.ts
node dts-google-apps-script-advanced/index.js data_3/classroom_v1.json > DefinitelyTyped/types/google-apps-script/apis/classroom_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/content_v2.json > DefinitelyTyped/types/google-apps-script/apis/content_v2.d.ts
node dts-google-apps-script-advanced/index.js data_3/dfareporting_v3_3.json > DefinitelyTyped/types/google-apps-script/apis/dfareporting_v3_3.d.ts
node dts-google-apps-script-advanced/index.js data_3/directory_v1.json > DefinitelyTyped/types/google-apps-script/apis/directory_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/docs_v1.json > DefinitelyTyped/types/google-apps-script/apis/docs_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/drive_v2.json > DefinitelyTyped/types/google-apps-script/apis/drive_v2.d.ts
node dts-google-apps-script-advanced/index.js data_3/driveactivity_v2.json > DefinitelyTyped/types/google-apps-script/apis/driveactivity_v2.d.ts
node dts-google-apps-script-advanced/index.js data_3/fusiontables_v2.json > DefinitelyTyped/types/google-apps-script/apis/fusiontables_v2.d.ts
node dts-google-apps-script-advanced/index.js data_3/gmail_v1.json > DefinitelyTyped/types/google-apps-script/apis/gmail_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/groupsmigration_v1.json > DefinitelyTyped/types/google-apps-script/apis/groupsmigration_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/groupssettings_v1.json > DefinitelyTyped/types/google-apps-script/apis/groupssettings_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/licensing_v1.json > DefinitelyTyped/types/google-apps-script/apis/licensing_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/mirror_v1.json > DefinitelyTyped/types/google-apps-script/apis/mirror_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/peopleapi_v1.json > DefinitelyTyped/types/google-apps-script/apis/peopleapi_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/reports_v1.json > DefinitelyTyped/types/google-apps-script/apis/reports_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/reseller_v1.json > DefinitelyTyped/types/google-apps-script/apis/reseller_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/sheets_v4.json > DefinitelyTyped/types/google-apps-script/apis/sheets_v4.d.ts
node dts-google-apps-script-advanced/index.js data_3/slides_v1.json > DefinitelyTyped/types/google-apps-script/apis/slides_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/tagmanager_v2.json > DefinitelyTyped/types/google-apps-script/apis/tagmanager_v2.d.ts
node dts-google-apps-script-advanced/index.js data_3/tasks_v1.json > DefinitelyTyped/types/google-apps-script/apis/tasks_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/urlshortener_v1.json > DefinitelyTyped/types/google-apps-script/apis/urlshortener_v1.d.ts
node dts-google-apps-script-advanced/index.js data_3/youtube_v3.json > DefinitelyTyped/types/google-apps-script/apis/youtube_v3.d.ts
node dts-google-apps-script-advanced/index.js data_3/youtubeanalytics_v2.json > DefinitelyTyped/types/google-apps-script/apis/youtubeanalytics_v2.d.ts
node dts-google-apps-script-advanced/index.js data_3/youtubepartner_v1.json > DefinitelyTyped/types/google-apps-script/apis/youtubepartner_v1.d.ts